### PR TITLE
Add "Edit Profile" section and a temporary login system   

### PR DESCRIPTION
**Pull request by shubham-padia**
*_please read this *_

-- Double-click on any field to edit it , press enter to Update it .
--No CSS styling has been added to the page (it would be futile to add the style till the common profile page has been decided).
-- The fields shown in the section are only for illustration as the fields for the profile page have not yet been decided.
--The LOGIN SYSTEM IS TEMPORARY and has only been added as we cannot work with the LDAP system at the moment.
---Demo can be found at http://shubhamp.in/profileserver/login.php (if you do not want to register , test user has email : johndoe@gmail.com and password : johndoe )

### CODE REVIEW

**Comment by vivekanand1101** [comment]
I didn't check the code for whether it works or not but i have a few suggestions:
1. Avoid giving more than one line gap within a block. Keep them to separate two functions/classes.
2. I don't know what you guys follow but i would prefer:
        `if (condition) { 
           } else {
           }`
   rather than putting the `{` or `else` in the next lines
3. `if count:` is a bit cooler than `if count == 0`
- in point two, because of md. it's coming in the same line, but i guess you understand what i mean.

**Comment by shubham-padia** [comment]
@vivekanand1101 thanks for the suggestions , will keep them in mind.

**Comment by SaptakS** [comment]
Also, @shubham-padia please try to squash your commits. So many commits for a single PR are not acceptable.For example, you should squash commits like `add Readme.md` and `Update Readme.md` and stuff like that.. Happy contributing.. :smiley:

**Comment by shubham-padia** [comment]
@SaptakS  squashed the unnecessary commits ( 2 commits to c4e97a9 and 2 to 405b3ac ).

**Pull request merged**
